import { ACTIVES, RULES, LEVELS, SKIN_TYPES, CONCERNS } from '/shared/data.js';
import { uiIcon, activeIcon } from '/shared/icons.js';
const $ = (s) => document.querySelector(s);
const icon = (name) => uiIcon(name, 'lg');
const esc = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const active = id => ACTIVES.find(a => a.id === id);
let saved = {};
try { saved = JSON.parse(localStorage.getItem('skinlab.neu-prototype.v1') || '{}') || {}; } catch {}
const state = { tab:'pairs', pair:['niacinamide','ha'], result:false, slot:0, skin:SKIN_TYPES.some(s=>s.id===saved.skin)?saved.skin:'combo', concern:CONCERNS.some(c=>c.id===saved.concern)?saved.concern:'dehydration', shelf:Array.isArray(saved.shelf)?saved.shelf.filter(id=>active(id)):[], time:'am', done:new Set(), theme:saved.theme || (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light') };
function persist(){try { localStorage.setItem('skinlab.neu-prototype.v1',JSON.stringify({skin:state.skin,concern:state.concern,shelf:state.shelf,theme:state.theme})); } catch { toast('Изменения доступны до закрытия страницы'); }}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),2600)}
const tabs=[['pairs','Сочетания','pairs'],['ideal','Подбор','sparkle'],['plan','Мой уход','plan'],['catalog','Активы','catalog'],['me','Профиль','me']];
function heading(kicker,title,sub){return `<div class="heading"><span class="small-label">${kicker}</span><h1>${title}</h1><p>${sub}</p></div>`}
function side(){return `<aside><section class="panel aside-card"><div class="emboss">${icon('leaf')}</div><h2>Уход начинается<br>с понимания кожи.</h2><p>У каждого актива своя задача.<br>Найдём те, что подходят именно вам.</p><button class="text-button" data-route="ideal">Подобрать мой уход <span>↗</span></button></section><div class="note"><span class="small-label">В ВАШЕМ ТЕМПЕ</span><p>Не обязательно менять всё сразу.<br>Начните с одного сочетания.</p></div></aside>`}
function getPair(){return RULES.find(([a,b])=>[a,b].includes(state.pair[0])&&[a,b].includes(state.pair[1]))}
function result(){const rule=getPair();return `<section class="result" data-tone="${rule?.[2]||'ok'}" role="status"><h3>${rule?esc(LEVELS[rule[2]].label):'Для этой пары пока нет правила'}</h3><p>${rule?esc(rule[3]):'Недостаточно данных в справочнике. Это не подтверждение безопасности сочетания.'}</p><button class="text-button" id="save-pair">Сохранить активы в мой уход ↗</button></section>`}
function pairs(){return heading('ЧТО С ЧЕМ СОЧЕТАТЬ','Хорошая пара.<br>Для вашей кожи.','Выберите два актива — разберёмся, как они работают вместе.')+`<div class="layout"><div><section class="panel"><div class="panel-header"><h2>Проверим сочетание</h2><span class="mini-tag">2 актива</span></div><div class="pair-stage">${state.pair.map((id,i)=>`${i?'<span class="pair-plus">+</span>':''}<button class="active-choice" data-slot="${i}" aria-label="Изменить актив ${i+1}: ${esc(active(id).name)}"><span class="orb">${activeIcon(active(id))}</span><b>${esc(active(id).name)}</b><small>${esc(active(id).inci)} · изменить</small></button>`).join('')}</div><button class="primary" id="check">${icon('pairs')} Проверить сочетание <span>↗</span></button><p class="under-button">Нажмите на актив, чтобы выбрать другой</p>${state.result?result():''}</section><section class="quick"><h3>Можно начать с этих пар</h3><div class="chips"><button class="chip" data-preset="retinol,niacinamide">Ретинол + ниацинамид</button><button class="chip" data-preset="vitc,spf">Витамин C + SPF</button><button class="chip" data-preset="retinol,aha">Ретинол + кислоты</button></div></section></div>${side()}</div>`}
function row(a,mode='detail'){return `<button class="row" data-${mode}="${a.id}"><span class="row-icon">${activeIcon(a)}</span><span><b>${esc(a.name)}</b><small>${esc(a.group)} · ${esc(a.inci)}</small></span><span class="row-end">${mode==='choose'?'+':'↗'}</span></button>`}
function catalog(){return heading('БИБЛИОТЕКА SKINLAB','Знакомимся с активами.','Понятно о том, что находится в вашей косметике.')+`<label class="search">${icon('search')}<input id="catalog-search" aria-label="Поиск по справочнику" placeholder="Найти актив или ингредиент"></label><div class="catalog-grid" id="catalog-list">${ACTIVES.map(a=>row(a)).join('')}</div>`}
function profileForm(){return `<label class="form-field"><span>Мой тип кожи</span><select id="skin">${SKIN_TYPES.map(s=>`<option value="${s.id}" ${s.id===state.skin?'selected':''}>${s.label}</option>`).join('')}</select></label><label class="form-field"><span>На чём сосредоточимся?</span><select id="concern">${CONCERNS.map(s=>`<option value="${s.id}" ${s.id===state.concern?'selected':''}>${s.label}</option>`).join('')}</select></label>`}
function ideal(){return heading('ИНДИВИДУАЛЬНЫЙ ПОДХОД','У вашей кожи<br>свои предпочтения.','Расскажите о ней немного — найдём подходящие активы в справочнике.')+`<div class="layout"><section class="panel">${profileForm()}<button class="primary" id="recommend">Найти активы ${icon('sparkle')}</button><div id="recommendations"></div></section>${side()}</div>`}
function plan(){const list=state.shelf.map(active).filter(a=>a.time==='ANY'||a.time===(state.time==='am'?'AM':'PM')).sort((a,b)=>a.layer-b.layer);return heading('МОЙ ЕЖЕДНЕВНЫЙ РИТУАЛ','Немного времени.<br>Только для себя.','Ваша полка активов и небольшие шаги заботы о коже.')+`<div class="layout"><section class="panel"><div class="segment">${['am','pm'].map((t,i)=>`<button data-time="${t}" class="${state.time===t?'selected':''}" aria-pressed="${state.time===t}">${icon(i?'moon':'sun')}${i?'Вечер':'Утро'}</button>`).join('')}</div><div class="steps">${list.length?list.map((a,i)=>`<div class="step"><button data-done="${a.id}" class="${state.done.has(state.time+a.id)?'done':''}" aria-pressed="${state.done.has(state.time+a.id)}" aria-label="Отметить ${esc(a.name)}">${state.done.has(state.time+a.id)?'✓':String(i+1).padStart(2,'0')}</button><div><h3>${esc(a.name)}</h3><p>${esc(a.inci)}</p></div><button data-remove="${a.id}" aria-label="Убрать ${esc(a.name)}">×</button></div>`).join(''):'<p class="empty">Здесь будет ваш уход.<br>Добавьте первый актив на полку.</p>'}</div><button class="primary" id="add-shelf" style="margin-top:28px">+ Добавить актив</button><p class="under-button">Полка прототипа. Проверяйте сочетания перед применением.</p></section>${side()}</div>`}
function me(){return heading('ЛИЧНОЕ ПРОСТРАНСТВО','Забота о себе.<br>По вашим правилам.','Настройки для вашего знакомства с новым SkinLab.')+`<div class="layout"><section class="panel"><h2>Профиль кожи</h2>${profileForm()}<button class="primary" id="save-profile">Сохранить профиль</button></section><section class="panel"><div class="emboss">${icon('auto')}</div><h2 style="margin-top:25px">Настроить настроение</h2><p>Попробуйте мягкий свет и глубокую тёмную тему.</p><button class="primary" id="theme-profile">Сменить тему</button><p class="under-button">Данные сохраняются только в этом браузере. Оплаты и Telegram не подключены.</p></section></div>`}
function render(){document.documentElement.dataset.theme=state.theme;$('#navigation').innerHTML=tabs.map(([id,label,ico])=>`<button data-route="${id}" class="${state.tab===id?'active':''}" ${state.tab===id?'aria-current="page"':''}>${icon(ico)}<span>${label}</span></button>`).join('');$('#view').innerHTML=({pairs,ideal,plan,catalog,me}[state.tab]||pairs)();}
function route(tab){state.tab=tabs.some(t=>t[0]===tab)?tab:'pairs';render();window.scrollTo(0,0)}
window.addEventListener('hashchange',()=>route(location.hash.slice(1)));
function openPicker(mode){state.pickerMode=mode;$('#dialog-title').textContent='Выберите актив';$('#search').parentElement.hidden=false;$('#search').value='';pickerList('');$('#picker').showModal();$('#search').focus()}
function pickerList(query){const list=ACTIVES.filter(a=>(a.name+' '+a.inci).toLowerCase().includes(query.toLowerCase())&&(state.pickerMode!=='pair'||a.id!==state.pair[1-state.slot]));$('#picker-list').innerHTML=list.length?list.map(a=>row(a,'choose')).join(''):'<p class="empty">Ничего не найдено. Попробуйте другое название.</p>'}
function detail(id){const a=active(id);$('#dialog-title').textContent=a.name;$('#search').parentElement.hidden=true;$('#picker-list').innerHTML=`<span class="small-label">${esc(a.inci)}</span><p class="detail-copy">${esc(a.what)}</p><h3>Что делает</h3><ul class="detail-copy">${a.benefits.map(b=>`<li>${esc(b)}</li>`).join('')}</ul><button class="primary" data-add="${a.id}">Добавить на мою полку</button>`;$('#picker').showModal()}
function add(id){if(!state.shelf.includes(id))state.shelf.push(id);persist();toast('Актив добавлен в «Мой уход»')}
$('#search-icon').innerHTML=icon('search');$('#search').addEventListener('input',e=>pickerList(e.target.value));$('#close-dialog').onclick=()=>$('#picker').close();$('#picker').addEventListener('click',e=>{if(e.target===$('#picker'))$('#picker').close()});
function theme(){state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;persist()}
document.addEventListener('change',e=>{if(e.target.id==='skin'||e.target.id==='concern'){state[e.target.id]=e.target.value;$('#recommendations')?.replaceChildren()}});
document.addEventListener('input',e=>{if(e.target.id==='catalog-search'){const found=ACTIVES.filter(a=>(a.name+' '+a.inci).toLowerCase().includes(e.target.value.toLowerCase()));$('#catalog-list').innerHTML=found.length?found.map(a=>row(a)).join(''):'<p class="empty">Такого актива пока нет в справочнике.</p>'}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
if(d.route){location.hash=d.route;return}if(d.slot!==undefined){state.slot=Number(d.slot);openPicker('pair');return}if(d.preset){state.pair=d.preset.split(',');state.result=true;render();return}
if(d.choose){if(state.pickerMode==='pair'){state.pair[state.slot]=d.choose;state.result=false}else add(d.choose);$('#picker').close();render();return}
if(d.detail){detail(d.detail);return}if(d.add){add(d.add);$('#picker').close();return}if(d.time){state.time=d.time;render();return}if(d.done){const k=state.time+d.done;state.done.has(k)?state.done.delete(k):state.done.add(k);render();return}if(d.remove){state.shelf=state.shelf.filter(id=>id!==d.remove);persist();render();return}
if(b.id==='check'){state.result=true;render()}if(b.id==='save-pair'){state.pair.forEach(id=>{if(!state.shelf.includes(id))state.shelf.push(id)});persist();toast('Оба актива сохранены в «Мой уход»')}
if(b.id==='add-shelf')openPicker('shelf');if(b.id==='theme'||b.id==='theme-profile')theme();if(b.id==='save-profile'){persist();toast('Профиль сохранён в этом браузере')}
if(b.id==='recommend'){persist();const found=ACTIVES.filter(a=>a.skin[state.skin]==='great'&&a.concerns.includes(state.concern)&&!a.drug);$('#recommendations').innerHTML=`<h3 style="margin-top:28px">Для вашего знакомства</h3><p>Совпадения по справочнику, не готовая схема ухода. Откройте актив, чтобы узнать больше.</p><div class="list">${found.length?found.slice(0,4).map(a=>row(a)).join(''):'<p>Точного совпадения нет. Попробуйте другую задачу или откройте библиотеку активов.</p>'}</div>`}
});
route(location.hash.slice(1));
